# Generated by Django 5.1.3 on 2024-11-16 13:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposCasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CCA', 'Casa Completa'), ('ACA', 'Apartamento Completo'), ('HP', 'Habitación Privado'), ('HC', 'Habitación Compartida'), ('CCO', 'Casa Compartida'), ('ACO', 'Apartamento Compartido')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BuscarCasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rangoPrecio', models.IntegerField(validators=[django.core.validators.MaxValueValidator(50000), django.core.validators.MinValueValidator(0)])),
                ('ubicacion', models.TextField()),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorBusqueda', to='authentication.userinfo')),
                ('tipoCasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_casa', to='posts.tiposcasa')),
            ],
        ),
    ]
