# Generated by Django 5.1.3 on 2024-11-16 14:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buscarcasa',
            name='tipoCasa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_casaBusqueda', to='posts.tiposcasa'),
        ),
        migrations.CreateModel(
            name='RentarCasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField()),
                ('cantidad_personas', models.IntegerField()),
                ('ubicacion', models.TextField()),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('lugares_importantes', models.TextField()),
                ('reglas_casa', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerCasa', to='authentication.userinfo')),
                ('tipoCasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_casaRenta', to='posts.tiposcasa')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenesRenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenes_renta')),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenesCasa', to='posts.rentarcasa')),
            ],
        ),
    ]
