# Generated by Django 5.1.3 on 2024-11-17 19:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('posts', '0002_alter_buscarcasa_tipocasa_rentarcasa_imagenesrenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentariosBusqueda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorPostBusqueda', to='authentication.userinfo')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentariosPostBusqueda', to='posts.rentarcasa')),
            ],
        ),
        migrations.CreateModel(
            name='ComentariosRenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorPostRenta', to='authentication.userinfo')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentariosPostRenta', to='posts.rentarcasa')),
            ],
        ),
    ]
