# Generated by Django 5.1.3 on 2024-11-18 00:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('posts', '0003_comentariosbusqueda_comentariosrenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ofertasBusqueda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorPostBusqueda', to='authentication.userinfo')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentariosPostBusqueda', to='posts.buscarcasa')),
                ('postOferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postOferta', to='posts.rentarcasa')),
            ],
        ),
        migrations.DeleteModel(
            name='ComentariosBusqueda',
        ),
    ]
